Part 2 preview
h4zzkR/poliyoy pull request #2
Opened 2021-04-18 15:10 UTC by h4zzkR

2021-05-02 17:55 UTC, h4zzkR commented
Второе ревью заканчивается на коммите f77e6cc521810630dcdc020c50252ad185136470

2021-05-03 15:17 UTC, Khabutdinov-Arslan requested changes

2021-05-03 15:17 UTC, Khabutdinov-Arslan commented on ui.py
> +    btn1 = PlaceEntityButton(text=f"V: {ENTITY_ID2COST[2]}", center_x=game_obj.w + game_obj.ui_margin_left,  # village
Variable naming

2021-05-03 15:17 UTC, Khabutdinov-Arslan commented on map/hexagonal_map.py
> +        if self.is_in_move_range(old_pos, new_pos):
Add CoR

2021-05-14 12:20 UTC, Khabutdinov-Arslan approved these changes

2021-05-14 12:21 UTC, merged